=== Benjigx/kmd/KMDTests/sites.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for sites to be tested",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "mangaUrl": {
        "type": "string"
      },
      "mangaName": {
        "type": "string"
      },
      "mangaCover": {
        "type": "string"
      }
    }
  }
}

=== Benjigx/kmd/KMDTests/sites.json
[
  {
    "name": "Tao Sect",
    "mangaName": "Dosanko Gal wa Namara Menkoi",
    "mangaUrl": "https://taosect.com/projeto/dosanko-gal-wa-namara-menkoi/",
    "mangaCover": "https://taosect.com/wp-content/uploads/2019/09/33949.jpg"
  },
  {
    "name": "LoveHug",
    "mangaName": "SHIJOU SAIKYOU NO MAHOU KENSHI, F RANK BOUKENSHA NI TENSEI SURU ~ KENSEI TO MATEI, 2 TSU NO ZENSE O MOTTA OTOKO NO EIYUUTAN ~ (MANGA) - RAW",
    "mangaUrl": "https://lovehug.net/1021/",
    "mangaCover": "https://s4.imfaclub.com/images/20200816/5f38ad760da96_5f38ad77917bb.jpg"
  },
  {
    "name": "Read Comic Online",
    "mangaName": "Mighty Morphin Power Rangers",
    "mangaUrl": "https://readcomiconline.to/Comic/Mighty-Morphin-Power-Rangers",
    "mangaCover": "https://2.bp.blogspot.com/-BbI2s9mqF5w/VtADsiU5PLI/AAAAAAAACIo/h9ZmCTvD2g4/s1600-Ic42/5.jpg"
  },
  {
    "name": "Manganelos",
    "mangaName": "Dr. Stone",
    "mangaUrl": "http://manganelos.com/manga/dr-stone",
    "mangaCover": "https://ww2.mangakakalots.com/mangaimage/dr_stone.jpg"
  },
  {
    "name": "NewToki",
    "mangaName": "섹서사이즈",
    "mangaUrl": "https://newtoki95.com/webtoon/307716?toon=%EC%84%B1%EC%9D%B8%EC%9B%B9%ED%88%B0",
    "mangaCover": "https://newtoki95.com/data/file/webtoon/763167241_5xO8ycEQ_090e3abfbae8499cd91063dffb6f49511af786c7.PNG"
  },
  {
    "name": "Read Comics Online",
    "mangaName": "Avengers (2018-)",
    "mangaUrl": "https://readcomicsonline.ru/comic/avengers-2018",
    "mangaCover": "https://readcomicsonline.ru/uploads/manga/avengers-2018/cover/cover_250x350.jpg"
  },
  {
    "name": "Zymk",
    "mangaName": "天醒之路",
    "mangaUrl": "https://www.zymk.cn/2463/",
    "mangaCover": "https://image.zymkcdn.com/file/cover/000/002/463.jpg-300x400"
  },
  {
    "name": "LimaScans",
    "mangaName": "Mato Seihei no Slave",
    "mangaUrl": "http://limascans.xyz/v2/manga/mato-seihei-no-slave/",
    "mangaCover": "http://limascans.xyz/v2/wp-content/uploads/2020/04/32386v5-193x278.jpg"
  },
  {
    "name": "Nhentai",
    "mangaName": "Ochiru",
    "mangaUrl": "https://nhentai.net/g/323041/",
    "mangaCover": "https://t.nhentai.net/galleries/1697981/cover.jpg"
  },
  {
    "name": "HiperCool",
    "mangaName": "Solmi's Channel",
    "mangaUrl": "https://hiper.cool/books/solmis-channel",
    "mangaCover": "https://static.hiper.cool/books/solmis-channel/solmis-channel-cover.jpg?revision=95"
  },
  {
    "name": "Hentai2Read",
    "mangaName": "Shokugeki no Sperm",
    "mangaUrl": "https://hentai2read.com/shokugeki_no_sperm/",
    "mangaCover": "https://img3.hentaicdn.com/hentai/cover/_S13224.jpg"
  },
  {
    "name": "MangaKakalot",
    "mangaName": "School Zone",
    "mangaUrl": "https://mangakakalot.com/manga/dg919090",
    "mangaCover": "https://avt.mkklcdnv6.com/19/j/18-1583497848.jpg"
  },
  {
    "name": "Manganelo",
    "mangaName": "Ore-Tachi No Party Wa Machigatteiru",
    "mangaUrl": "https://manganelo.com/manga/oretachi_no_party_wa_machigatteiru",
    "mangaCover": "https://avt.mkklcdnv6.com/21/h/16-1583494233.jpg"
  },
  {
    "name": "ProjetoScanlator",
    "mangaUrl": "https://projetoscanlator.com/manga/nanatsu-no-taizai/",
    "mangaName": "Nanatsu no Taizai",
    "mangaCover": "https://projetoscanlator.com/wp-content/uploads/2019/06/Poster-1-1-193x278.jpg"
  },
  {
    "name": "GekkouScans",
    "mangaUrl": "http://leitor.gekkouscans.com.br/manga/maou-gakuen-no-hangyakusha",
    "mangaName": "Maou Gakuen no Hangyakusha",
    "mangaCover": "http://leitor.gekkouscans.com.br//uploads/manga/maou-gakuen-no-hangyakusha/cover/cover_250x350.jpg"
  },
  {
    "name": "SaikaiScan",
    "mangaUrl": "https://saikaiscan.com.br/manhuas/golden-time-gt/56",
    "mangaName": "Golden Time (GT)",
    "mangaCover": "https://saikaiscan.com.br/media/cache/20/56/20560738d51e28604358c951a9dd0790.png"
  },
  {
    "name": "NeoxScanlator",
    "mangaUrl": "https://neoxscans.com/manga/hunter-age/",
    "mangaName": "Hunter Age",
    "mangaCover": "https://neoxscans.com/wp-content/uploads/2020/11/Hunter-Age-1-193x278.jpg"
  },
  {
    "name": "DropeScan",
    "mangaUrl": "https://dropescan.com/manga/tomb-raider-king/",
    "mangaName": "Tomb Raider King",
    "mangaCover": "https://i2.wp.com/dropescan.com/wp-content/uploads/2020/08/TRK.jpg?fit=266%2C359&ssl=1"
  },
  {
    "name": "MangaZuki",
    "mangaUrl": "https://mangazuki.me/manga/apotheosis/",
    "mangaName": "Apotheosis",
    "mangaCover": "https://mangazuki.me/wp-content/uploads/2019/05/i295980-193x278.jpg"
  },
  {
    "name": "MundoAvatar",
    "mangaUrl": "https://leitor.mundoavatar.com.br/manga/promessa/",
    "mangaName": "A Promessa (#01)",
    "mangaCover": "https://leitor.mundoavatar.com.br/wp-content/uploads/2020/08/promessa2-193x278.jpg"
  },
  {
    "name": "YaoiToshokan",
    "mangaUrl": "https://www.yaoitoshokan.com.br/manga/a-lucky-coin/",
    "mangaName": "A Lucky Coin",
    "mangaCover": "https://www.yaoitoshokan.com.br/wp-content/uploads/2020/08/rROHYYKHa8HlWy3U7kHm8eI5JAZfMxWwoY7jjzFcwmDVB-N.jpg"
  },
  {
    "name": "TsukiMangas",
    "mangaName": "The Sword of Glory",
    "mangaUrl": "https://tsukimangas.com/obra/2088/the-sword-of-glory",
    "mangaCover": "https://tsukimangas.com/obra/imgs/2088.jpg?t=1609918237744"
  },
  {
    "name": "Opex",
    "mangaName": "One Piece",
    "mangaUrl": "https://onepieceex.net/mangas/",
    "mangaCover": "https://onepieceex.net/mangareader/sbs/capa/grande/Volume_1.jpg"
  },
  {
    "name": "HQDragon",
    "mangaName": "18 Dias",
    "mangaUrl": "https://hqdragon.com/hq/mzc4nq/3785-18-dias",
    "mangaCover": "https://dataimg.hqdragon.com/assets/uploads/mangas/c1534912.jpg"
  },
  {
    "name": "UnionMangas",
    "mangaName": "Boku no Hero Academia",
    "mangaUrl": "https://unionmangas.top/perfil-manga/boku-no-hero-academia-pt-br",
    "mangaCover": "https://unionmangas.top/assets/uploads/mangas/f34fef22.jpg"
  },
  {
    "name": "YesMangas",
    "mangaName": "One Punch-Man",
    "mangaUrl": "https://yesmangas1.com/manga/one-punch-man-ym21573",
    "mangaCover": "https://img-yes.filestatic1.xyz/mangas_files/one-punch-man/image_one-punch-man_full.webp"
  },
  {
    "name": "MangaLivre",
    "mangaName": "Boku no Hero Academia",
    "mangaUrl": "https://mangalivre.net/manga/boku-no-hero-academia/1319",
    "mangaCover": "https://static3.mangalivre.com/capas/fFNEvtskJ9_rLiZYuUEyAw/1319/5f8b2ac064a49external_cover.jpg?quality=100"
  },
  {
    "name": "Leitor.Net",
    "mangaName": "NieR: Automata - 2B Is A Little Bit Silly (Doujinshi)",
    "mangaUrl": "https://leitor.net/manga/nier-automata---2b-is-a-little-bit-silly-doujinshi/7576",
    "mangaCover": "https://static3.leitor.net/covers/9duMhzDRNjNjSufSoODrrQ/7576/external_cover.jpg?quality=100"
  },
  {
    "name": "Manga Host",
    "mangaUrl": "https://mangahosted.com/manga/boku-no-hero-academia-mh36655",
    "mangaName": "Boku no Hero Academia",
    "mangaCover": "https://img-host.filestatic1.xyz/mangas_files/boku-no-hero-academia/image_boku-no-hero-academia_full.jpg"
  },
  {
    "name": "AnimaRegia",
    "mangaUrl": "https://animaregia.net/manga/shakunetsu-no-niraikanai-ptbr",
    "mangaName": "Shakunetsu no Niraikanai",
    "mangaCover": "https://animaregia.net/uploads/manga/shakunetsu-no-niraikanai-ptbr/cover/cover_250x350.jpg"
  },
  {
    "name": "Comic Space",
    "mangaUrl": "https://www.acomic.space/manga/4-cut-hero",
    "mangaName": "4 Cut Hero",
    "mangaCover": "https://www.acomic.space/uploads/manga/4-cut-hero/cover/cover_250x350.jpg"
  },
  {
    "name": "MangaDex",
    "mangaUrl": "https://mangadex.org/title/51808/dungeon-ni-deai-wo-motomeru-no-wa-machigatteiru-darou-ka-ii",
    "mangaName": "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka II",
    "mangaCover": "https://mangadex.org/images/manga/51808.jpg?1596898222"
  }
]
